# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        main:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: main
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                default_target_path: /dashboard
                enable_csrf: true
            logout:
                path: app_logout
                target: /dashboard

    # access_control:
    #     - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/admin, roles: ROLE_ADMIN }
    #     - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]
        ROLE_USER: [ROLE_USER]
